DROP TABLE ITAG_RECORDS IF EXISTS;

CREATE TABLE ITAG_RECORDS(
     RECORD_ID INT NOT NULL PRIMARY KEY,
     TAG_AGENCY_ID VARCHAR(20) ,
     TAG_SERIAL VARCHAR(20) ,
     TAG_STATUS VARCHAR(20),
     TAG_ACCOUNTINFO VARCHAR(20)
);



DROP TABLE ICLP_RECORDS IF EXISTS;

CREATE TABLE ICLP_RECORDS(
     RECORD_ID INT NOT NULL PRIMARY KEY,
     LIC_STATE VARCHAR(20),
     LIC_NUMBER VARCHAR(20),
     LIC_TYPE VARCHAR(20),
     TAG_AGENCY_ID VARCHAR(20) ,
     TAG_SERIAL_NUMBER VARCHAR(20)
);



DROP TABLE TVL_RECORDS IF EXISTS;

CREATE TABLE TVL_RECORDS(
     RECORD_ID INT NOT NULL PRIMARY KEY,
     TAG_AGENCY_ID VARCHAR(20) ,
     TAG_SERIAL VARCHAR(20) NOT NULL PRIMARY KEY,
     TAG_STATUS VARCHAR(20),
     TAG_ACCOUNTINFO VARCHAR(20),
     LIC_STATE VARCHAR(20),
     LIC_NUMBER VARCHAR(20),
     LIC_TYPE VARCHAR(20)
);